# Generated by Django 4.1 on 2022-09-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=255, verbose_name='비밀번호'),
        ),
    ]
