# Generated by Django 4.1 on 2022-09-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weather',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='날씨'),
        ),
    ]
